jetstream {
  store_dir: "/data/jetstream"
  max_mem_store: 2GB
  max_file_store: 10GB
}

http: 8222

websocket {
  port: 4443
  no_tls: true
}

server_name: SUPABASE_NATS

accounts {
  APP {
    jetstream: enabled

    users = [
      {
        user: "admin"
        password: "admin_pass"
        permissions {
          publish = ["$JS.>","users.*","forms.*","universal.*"]
          subscribe = ["$JS.>","users.*","forms.*","universal.*"]
        }
      },
      {
        user: "app_user"
        password: "app_pass"
        permissions {
          publish = ["users.*","forms.*","universal.*"]
          subscribe = ["users.*","forms.*","universal.*"]
        }
      }
    ]
  }
}
